[env]
VC_BUILD_DIR="D:\\Program Files\\MVS\\VC\\Auxiliary\\Build\\vcvars64.bat"

[env.development]
TARGET_PATH = "target/x86_64-pc-windows-msvc/debug"

[env.production]
TARGET_PATH = "target/x86_64-pc-windows-msvc/release"
BUILD_RELEASE = "--release"

[tasks.build-driver]
script = '''
cargo b %BUILD_FLAGS%
'''

[tasks.rename]
ignore_errors = true
script = '''
cd %TARGET_PATH%
del /f meta_driver.sys
rename meta_driver.dll meta_driver.sys
'''

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = '''
call "%VC_BUILD_DIR%"
if not exist driver_cert.crt ( powershell -file sign.ps1 ) else ( echo Certificate already exists. )
'''